### ISSUE TITLE
As a user I would like tags for breaking changes

### ISSUE THREAD

**Issue by tnebrs** [Budabot/Tyrbot#114]
No version tags means no ability to roll back breaking changes. Configuration object has changed between 0.5 and 0.7.

**Comment by bigwheels16** [comment]
until we do a v1.0 release, all changes have the potential to be breaking.

we do try to notify in the discord when a change like this is coming, as we did for these last changes so it's recommended to join the discord.

that being said, we probably won't have any more changes like that until after 1.0

**Comment by bigwheels16** [comment]
I've bumped the version to 1.0 now to indicate that we are now "stable".  So there should not be any more breaking changes.  And if there are, they will be released under a version 2.
