### ISSUE TITLE
Items command has stopped working in Budabot

### ISSUE THREAD

**Issue by Ginger201** [Budabot/Tyrbot#118]
Just in the last few days our install of Budabot 3.5_GA has been unable to find the items database on Github and the "!Items" has stopped functioning.  I am a Novice at chatbots, could anyone help with instructions how to fix this?  Or is happening to others too?

Ginger201

**Comment by Teeko7** [comment]
This repository is for Tyrbot, not Budabot. Per the Budabot repository, it is now archived, marked read only, and not supported. If you are unable to fix the problems you encounter with budabot, we recommend updating to a new, supported bot.
![image](https://user-images.githubusercontent.com/3143750/140792297-676b8227-7677-4a35-972c-bd9183086821.png)


Tyrbot is a reimagining of budabot written in python, and Nadybot is a continuation of the original budabot project.

**Comment by Ginger201** [comment]
Hi,

I have not switched to the Tyrbot because I don't know anything about
Python.  Is the Nadybot written in the language or operating system that
Budabot was written in?  So I won't need to download a new software?  Can I
"import" my Budabot files or ??? into Nadybot?

Thank you,

Jayne

**Comment by Teeko7** [comment]
Nadybot is a continuation of budabot. Ultimately it doesn't matter what any
bot is written in if you want to run one. Either one can fulfill the same
rules as budabot. For support for Tyrbot or Nadybot please visit their
respective repositories, wiki, and the discord channels associated with
them.
