### ISSUE TITLE
Cancel raffle not working

### ISSUE THREAD

**Issue by Hughp135** [Budabot/Tyrbot#17]
`raffle_controller.py", line 38, in raffle_cancel_cmd
    self.job_scheduler.cancel_job(self.raffle.scheduled_job.id)
AttributeError: 'int' object has no attribute 'id'`

note: on rk2019 and sqlite db

**Comment by bigwheels16** [comment]
thanks for reporting! i'll take a look

**Comment by bigwheels16** [comment]
this should be fixed now! https://github.com/Budabot/Tyrbot/commit/1aec38a586c1a010aabd2ddf158d7e96624b406f
