### ISSUE TITLE
Permissions with subcommand

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#19]
Subcommands do not have specific permissions, which makes certain commands very unsafe. Including !loot, which is enabled for "all" by default, makes it so anyone can do !loot remitem, !loot clear, and !loot roll. This should be remedied by either changing these to other commands within a same "loot module" or "raid module". This could also be remedied by having permissions assigned to subcommands.

**Comment by bigwheels16** [comment]
fixed with https://github.com/Budabot/Tyrbot/commit/29140c6be16b885a2e69d5e147b6cbe052ecd809
