### ISSUE TITLE
Whois with dimension param

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#22]
Please add a dimension param to whois similar to the history command

**Comment by bigwheels16** [comment]
this is going to be a lot harder than initially since the char id is expected when doing lookups

**Comment by Dustify** [comment]
I might be missing the point but do we need a 'pork-2019' label?

**Comment by bigwheels16** [comment]
the point is to lookup RK5 chars from RK6 and vice-versa
