### ISSUE TITLE
Online alignment discord

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#25]
Output of !online in discord should have proper alignment with name/side/level/profession, etc.

**Comment by Dustify** [comment]
@Teeko1993 can you confirm this is still relevant, I'm seeing the same data in-game vs discord:
![image](https://user-images.githubusercontent.com/626198/56069013-ee7ae180-5d78-11e9-8f00-0c8a09ef1731.png)
![image](https://user-images.githubusercontent.com/626198/56069023-f76bb300-5d78-11e9-8d72-eecd8aaf5a21.png)

Unless I'm being silly....

**Comment by Teeko1993** [comment]
Yes that is correct, it's how it's currently shown. If you have several people online it looks like this:
![image](https://user-images.githubusercontent.com/3143750/56071435-76062780-5d5c-11e9-883c-fedd1afcd3ce.png)

What I meant by aligning the text was making it so all levels, alignment, and professions were in line going down the list

**Comment by Dustify** [comment]
Ah sorry, when you said alignment I was thinking of side, rather than physical alignment - will look into it but I think the only way to do this in discord will be monospaced output, working on the longest string in each 'column'

**Comment by Teeko1993** [comment]
Ah yes that was the way I had thought of as well.

**Comment by Dustify** [comment]
PR raised:
https://github.com/Budabot/Tyrbot/pull/33

Output looks like this:
![image](https://user-images.githubusercontent.com/626198/56074456-1125ee00-5dab-11e9-98dc-ceeda777912e.png)

**Comment by Dustify** [comment]
Disregard my previous comment!

**Comment by Dustify** [comment]
PR raised:
https://github.com/Budabot/Tyrbot/pull/36

Output: 
![image](https://user-images.githubusercontent.com/626198/56075106-1be58080-5db5-11e9-84ac-8f7a7abbc06d.png)

**Comment by Teeko1993** [comment]
Why does it seem like it is not the same for the person in the private channel? I assume it is the AI levels, but wouldn't those be accounted for in the "max space needed" there?

**Comment by bigwheels16** [comment]
I think the max spacing is on a per-channel basis

**Comment by Teeko1993** [comment]
I mean the max amount of characters that the ai level could be. Should be aligned at the left like the rest of the columns

**Comment by Dustify** [comment]
It's split into 4 'columns' presently: name, 'levels', side and prof. and as @bigwheels16 mentioned it's done on a per-channel basis.

**Comment by Teeko1993** [comment]
Is that better than the uniform spacing the entire way down?

**Comment by Dustify** [comment]
Given that the org / priv channels are split, I'd argue the benefit to the end user is marginal at best - regardless, I'm not spending any more time on this one, maybe someone else will pick it up.

**Comment by KristinHansen** [comment]
Did anyone test this with other outputs than just the embedded ones? Primarily the "colored" (apache) markup.

**Comment by Teeko1993** [comment]
Those were removed I believe. The only outputs are "plain" for messages and embedded for command results.

**Comment by jroovers** [comment]
'new style' string formatting supports easy aligning https://pyformat.info/#param_align

I might take a look at this

coloring should be a matter of adding  language name after the backticks (```).
Example (apache, python, css):
![image](https://user-images.githubusercontent.com/11883404/56100365-1b192f80-5f18-11e9-8461-f0142a6d5eaa.png)

**Comment by bigwheels16** [comment]
@KristinHansen I ended up removing the different discord outputs setting.  I thought you were in the channel when we were talking about it but maybe not.  The problem was that it made it very hard when writing commands for discord since each command had to provide three different outputs for each of the different format types, if you wanted the outputs to look good in the discord channel.  So now, all commands use the embed type, and then chat relay messages use plain, or maybe colored, I can't remember which.

**Comment by Teeko1993** [comment]
It's the plain type. Colored took up a very large space in the discord channel for the bot to speak, which made conversations between discord and org chat(main selling point of the discord module) much more difficult

**Comment by jroovers** [comment]
![image](https://user-images.githubusercontent.com/11883404/56128938-513ec980-5f81-11e9-9b18-08743b623d33.png)

**Comment by KristinHansen** [comment]
I was not aware of that, no. Was just curious if it had been tested with the three output types (which it obviously hasn't, as it's not relevant anymore with the latest changes).
