### ISSUE TITLE
Port !track from Budabot

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#28]
Tracklist is useful for keeping track of important people outside the org without using your own friendslist. This feature is missing in Tyrbot.

**Comment by bigwheels16** [comment]
@Minidodo1 is this something you want to work on since you already have the code for it?

**Comment by bigwheels16** [comment]
closing since this using the bot is not a good approach for this

**Comment by bigwheels16** [comment]
wrong issue, reopening

**Comment by bigwheels16** [comment]
this is now done
