### ISSUE TITLE
Leaderecho

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#34]
Leaderecho currently defaults to off and must be turned ON on a per raid basis. Budabot had this defaulted to ON and was turned OFF with a setting in the bot. How should this be handled?
1. As-is, defaulted to off and only turned on for a single raid at a time
2. Default to on and turned off for a single raid at a time
3. have a setting in the bot that turns it on/off globally

**Comment by KristinHansen** [comment]
I can add a setting that'll allow you to decide whether it should be on by default or not, as in, when someone takes the role as leader, it'll automatically flip on, if the global setting is set to true.
What ye say, @bigwheels16?

**Comment by bigwheels16** [comment]
Do we have any idea how many people would prefer it on by default compared to how many people prefer it off?  If it's close to a 50/50 split, then I would say we need a setting.

But if it's like 90% or more that all prefer it one way, we should not add a setting and just default it to what is most common.

Do we have any idea what most people prefer here?

**Comment by KristinHansen** [comment]
It was on/off for me when we did any raiding and were using Budabot. It really came down to who was participating in the raid. I'd probably personally leave it off by default. But generally speaking, I can see how this definitely could be a personal preference, where others might have a more strict raiding culture (we were quite carte blanche when raiding internally with the org, even when we had outsiders join, so I'm probably not the best example for this).

**Comment by Teeko1993** [comment]
I always had it on, for the simple reason that with the amount of conversations happening in raid chat, the bot, and team chat, leaderecho just made it super easy to see when to move if people weren't super paying attention to the raid.

**Comment by bigwheels16** [comment]
Alright, let's add a setting for this then.

**Comment by KristinHansen** [comment]
Resolved with #52.
