### ISSUE TITLE
Discord Module Voice Channel Enhancements

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#37]
Allow the discord module to "watch" specific voice channels and report when users join/leave those channels and when they go to the designated AFK channel.

**Comment by KristinHansen** [comment]
Could you elaborate on the last part regarding the afk channel?

**Comment by KristinHansen** [comment]
And by watching channels, you want to be told, in text (ingame?), that person A joined channel B, correct?

**Comment by Teeko1993** [comment]
Yes, so if the bot is "watching" specific channels, it will see joins and leaves from those channels, where the user came from/went to. The AFK channel bit is the same as that, doesn't need to have that specifically added now that I think about it.

**Comment by bigwheels16** [comment]
@Teeko1993 can you add a use case for this?  Just a simple scenario where this would be useful and generally applicable.

**Comment by Teeko1993** [comment]
You have a discord server and specific channels for AO and you want to see when people join the channels and leave the channels. People may not know who randomly left the discord, or who joined but hasn't spoke yet. Maybe a better solution would be to have a way to "check" who is in discord at any given time? Like an !online for specific discord voice channels?

**Comment by Hughp135** [comment]
I can see some benefit of being able to see how many people are in voice channels through the bot.

In my opinion, it would be neater if user's voice channel status would be somehow appended to the existing !online command.

**Comment by bigwheels16** [comment]
going to close as this isn't something we are going to support right now
