### ISSUE TITLE
Gridnet Module Improvements

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#42]
The Gridnet module should have a one command "off" switch. Also we should have separate settings for whether or not the bot spams to org chat and private channel.

**Comment by Dustify** [comment]
https://github.com/Dustify/Tyrbot/commit/bdb73d4cb7ec6246405486e7e691913ee1fd5527 Commit for review before I take it any further

**Comment by bigwheels16** [comment]
I added some comments on your fork

**Comment by Dustify** [comment]
Made a comment on my previous commit but the mechanism for closing the connection seems to be working, wouldn't mind if someone else could test please :)

**Comment by bigwheels16** [comment]
@Dustify can you make a pull request for this?

**Comment by Teeko1993** [comment]
Closed as settings/events discussion is still up in the air on how to handle them from a user's standpoint.
