### ISSUE TITLE
Raid Module

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#43]
Currently, if you start a raid and set a min_level there is no way to override that for a character that recently(since the last update of the character info) met that requirement. There should be a !raid add charname command so a raider can be manually added.

**Comment by KristinHansen** [comment]
@Teeko1993 
I'll currently working on rewriting the loot controller. This will affect the raid module (auctions primarily). But I've meant to take a look at the raid module and probably rewrite some parts of it.
