### ISSUE TITLE
Gridnet automatically on

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#44]
Currently, gridnet is automatically enabled despite RK5 bots having no use for it. This should be changed. Possible resolutions could be allowing the bot to check what dimension it is on and selecing the default based on the dimension, or forcing it off and allowing players to turn it on with a single command, see issue #42

**Comment by Dustify** [comment]
Maybe a boolean setting 'Only connect to Gridnet on RK6' defaulted to True?

There may be a nicer way...

**Comment by Teeko1993** [comment]
But Gridnet could be implemented on RK5 using lightnet's infrastructure. So we don't want to hardcode a disable here, I don't think.

**Comment by Dustify** [comment]
I'm not suggesting a hardcode but a configurable setting that means it won't attempt a connection to Gridnet on RK5 by default - in the future the default could be changed or the setting removed entirely

**Comment by Teeko1993** [comment]
Oh sorry I didn't see the "defaulted to true" part. My fault. A setting with a default dependent on the server makes sense to me.

**Comment by bigwheels16** [comment]
I will make it so that it only connects to Gridnet on RK6, and then revisit it when I implement it for RK5.
