### ISSUE TITLE
Org Module issue

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#49]
In the org module, there are two settings:
private_channel_joined - Notify when a character joins the private channel [Enabled] On Off
private_channel_left - Notify when a character leaves the private channel [Enabled] On Off

Each of these should be split to have separate settings per channel, so you can have the notification in the private channel and/or the notification in the org channel.

**Comment by bigwheels16** [comment]
what is the use case for this request?

**Comment by Teeko1993** [comment]
An org raid bot that is a member of the org. You don't want people joining the private chat to be announced to the org chat. At least that's my specific use case.

**Comment by bigwheels16** [comment]
this should be addressed through the message_hub_service

**Comment by bigwheels16** [comment]
this is done
