### ISSUE TITLE
Should be an option to relay bot messages from org chat/private channel to discord

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#74]
Should be an option to relay bot commands from org chat/private channel to discord such as player logins/logouts, joining/leaving the private channel, item lookups, etc. This could be useful to make the channels feel more linked.

**Comment by bigwheels16** [comment]
can add logins, logouts, joining and leaving private channel, but command and command output is problematic since we don't have a good way to display aoml in discord
