### ISSUE TITLE
!items results could be more concise

### ISSUE THREAD

**Issue by Teeko1993** [Budabot/Tyrbot#75]
When the !items lookup only has a few results, the results should be given in the channel the lookup was requested in(tells, org chat, private channel, etc). This is similar to how budabot handles item lookups.

**Comment by bigwheels16** [comment]
the code to change is here: https://github.com/Budabot/Tyrbot/blob/53ad80f56eabaafcecf324ea05d5935b84e1f80e/modules/standard/items/items_controller.py#L49-L73

**Comment by Teeko1993** [comment]
Solved with https://github.com/Budabot/Tyrbot/commit/239d03da1ff8db76793c3e41b611d7639ec94c3d
