### ISSUE TITLE
Wont start on FreeBSD

### ISSUE THREAD

**Issue by salvoza** [Budabot/Tyrbot#92]
I have downloaded and installed the application. I am getting the following error:

Traceback (most recent call last):
  File "bootstrap.py", line 2, in <module>
    from core import config_creator
  File "/home/user/Tyrbot-master/core/config_creator.py", line 3, in <module>
    import hjson
ModuleNotFoundError: No module named 'hjson'

It cycles until I end the task. I have hjson installed:

Name: hjson
Version: 3.0.1
Summary: Hjson, a user interface for JSON.
Home-page: http://github.com/hjson/hjson-py
Author: Christian Zangl
Author-email: laktak@cdak.net
License: MIT License
Location: /usr/local/lib/python3.6/site-packages
Requires:
Required-by:

And pip list shows:
hjson                  3.0.1

I'm not sure what else to do here, please can you help?

**Comment by einarf** [comment]
How you you start the application?

**Comment by salvoza** [comment]
I found the error - was silly user error - it was clashing with Pythion 3.7
